[project]
name = "chatbot-tui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.76.0",
    "textual>=3.1.1",
    "toolkitr>=0.3.2",
]

[dependency-groups]
dev = [
    "textual-dev>=1.7.0",
]
